homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('blog/', views.blog, name='blog'),
]

jadwalKegiatan/urls.py
from django.urls import path
from . import views

app_name = 'jadwalKegiatan'

urlpatterns = [
    path('', views.jadwal, name='jadwal'),
    path('delete/<int:delete_id>', views.delete, name='delete')
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('jadwal/',include('jadwalKegiatan.urls', namespace='jadwal')),
]

homepage/models.py
from django.db import models

# Create your models here.

jadwalKegiatan/models.py
from django.db import models
# from django.forms import ModelForm

class JadwalKegiatan(models.Model):
    kegiatan = models.CharField(max_length=27)
    kategori = models.CharField(max_length=27)
    tempat = models.CharField(max_length=27)
    jam = models.TimeField()
    tanggal = models.DateTimeField()
    
    def __str__(self):
        return self.kegiatan


# Create your models here.

jadwalKegiatan/forms.py
from django import forms
from .models import JadwalKegiatan

class JadwalKegiatanForm(forms.ModelForm):
    class Meta:
      model = JadwalKegiatan
      fields = '__all__'
      widgets = {
        'tanggal' : forms.SelectDateWidget()
      }

homepage/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
  return render(request, 'index.html')

def blog(request):
  return render(request, 'blog.html')

jadwalKegiatan/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import JadwalKegiatan
from .forms import JadwalKegiatanForm

# Create your views here.
def jadwal(request):
  form = JadwalKegiatanForm(request.POST or None)
  jadwal = JadwalKegiatan.objects.all()

  if request.method == "POST":
    if form.is_valid():
      form.save()
      return redirect('/jadwal')

  return render(request, 'jadwal.html', {
    'form' : form,
    'jadwal' : jadwal
  })

def delete(request, delete_id):
  JadwalKegiatan.objects.filter(id=delete_id).delete()
  return redirect('jadwal:jadwal')

homepage/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      href="https://fonts.googleapis.com/css?family=Gabriela|Poppins&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.css' %}" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <title>Story 4</title>
  </head>
  <body>
    <div id="header"></div>
    <div class="sticky-top bg-white">
      <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light">
          <a class="navbar-brand" href="#">RR</a>
          <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a
                class="nav-item nav-link"
                href="{% url 'homepage:index' %}#header"
                >Beranda</a
              >
              <a
                class="nav-item nav-link"
                href="{% url 'homepage:index' %}#proyek"
                >Proyek</a
              >
              <a
                class="nav-item nav-link"
                href="{% url 'homepage:index' %}#kontak"
                >Kontak Saya</a
              >
              <a
                class="nav-item nav-link"
                href="{% url 'homepage:blog' %}#header"
                >Blog</a
              >
              <a
                class="nav-item nav-link"
                href="{% url 'jadwalKegiatan:jadwal' %}#header"
                >Jadwal</a
              >
            </div>
          </div>
        </nav>
      </div>
    </div>
    {% block content %} {% endblock %}
    <a href="#header" class="back-to-top">Tekan untuk kembali ke atas</a>

    <script
      src="https://kit.fontawesome.com/025b3a9369.js"
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
  </body>
</html>

homepage/templates/blog.html
{% extends "base.html" %} {% block content %} {% load static %}
<div class="lead-text">
  <h1>BLOG</h1>
  <div class="red-line"></div>
</div>

<div class="container">
  <div class="blog">
    <h1 class="title">Hidup saya di kuliah</h1>
    <p class="blog-text">
      Perkenalkan saya Reynard ingin menyampaikan keluh kesah saya selama
      berkuliah di Fasilkom UI. Disini kondisi yang saya rasakan cukup campur
      aduk, bagaimana tidak, disini banyak teman-teman yang asik serta wibu dan
      tugas yang rasanya membunuh saya pelan-pelan. Tak seperti biasanya, pada
      tanggal 24 September 2019, terdengar bahwa salah satu teman sebelah kos
      saya mendapatkan musibah. Namanya Delit. Beliau mengalami kecelakaan motor
      di salah satu jalan yang ada di Jakarta (disamarkan). Saya pun baru
      mendengar kabar tersebut satu hari setelah kejadian. Tak perlu pikir
      panjang, saya yang waktu itu lagi ada rapat suatu kepanitiaan langsung
      menjenguknya di RS UI. Diberi tahu kakaknya, ia dirawat di kamar
      301-Sayyid. Saya ketemu temen saya dulu, sampai jumpa nanti!
    </p>
  </div>
  <div class="blog">
    <h1 class="title">
      Tadi wudhu ada yang lucu!
    </h1>
    <p class="blog-text">
      Tadi ada yang lucu saat wudhu! Ada yang wudhu tapi lupa membuka topi. Saya
      dan wildan bingung kenapa tidak dibuka. Kita liatin terus tetapi tidak
      dibuka-buka. Ternyata dia hanya cuci muka. Sungguh ambigu bukan? hehe.
      Memang kalau lagi lelah, pikiran jadi kemana-mana. Saya sekarang lagi
      lelah karena PR KEBANYAKAN!!! Contohnya adalah PPW, PPM, ADBIS, SDA, dan
      ALIN. Contoh itu merupakan seluruh SKS saya semester ini. Artinya semua
      pelajaran saya ada tugas. yasudahlah mau diapakan lagi. Doakan saya ya
      semuanya!
    </p>
  </div>
  <div class="blog">
    <h1 class="title">
      Kak pewe ikut demo!?
    </h1>
    <p class="blog-text">
      Demo tugas maksud saya hehe. Sekarang saya akan menjelaskan mengenai tugas
      PPW yang saya berhasil kerjakan dalam kurun waktu satu hari. Kenapa saya
      kerjakan dalam waktu satu hari? Karena dari pertama kali tugas keluar
      selalu tidak ada waktu untuk mengerjakan. Sabtu minggu saya saja penuh
      dengan kegiatan Compfest dan PMB yang dimulai jam 6 pagi. Lelah sekali ya
      keliatannya! Tugas ini saya kerjakan senin dari jam 3 sore sampai jam 8
      malam dan saya lanjutkan lagi jam 12 siang besoknya. Desain berhasil saya
      bikin menarik, tapi menarik bagi saya saja. Semoga saya dapat nilai 4
      untuk semua sheet tugas PPW saya kalau tidak saya akan sedih. Sudah sampai
      situ saja sekarang. Ditunggu ya postingan selanjutnya!
    </p>
  </div>
</div>
{% endblock %}

homepage/templates/index.html
{% extends "base.html" %} {% block content %} {% load static %}
<div class="bg-gray">
  <div class="container">
    <div class="header-flex-wrapper">
      <div class="header-image-wrapper">
        <img src="{% static 'images/header-image.png' %}" alt="" />
      </div>
      <div class="text">
        <h1>Reynard Adha Ryanda</h1>
        <p class="subtitle">Mereka panggil saya Rey</p>
        <p>
          Halo! Saya adalah salah satu pejuang bangsa yang lahir pada tanggal
          <span class="red-font">16 Maret 2000</span>. Maksud saya pejuang
          bangsa adalah saya mahasiswa di
          <span class="red-font">Universitas Indonesia</span>, universitas yang
          sering dipanggil masyarakat luas sebagai universitas perjuangan. Saya
          sekarang sedang belajar
          <span class="red-font">Sistem Informasi</span> di
          <span class="red-font">Fakultas Ilmu</span>
          Komputer. Setelah liburan semester dua, saya lumayan
          <span class="red-font">tertarik dengan web development.</span>
        </p>
      </div>
    </div>
  </div>
</div>

<div id="proyek"></div>
<div class="lead-text">
  <h1>PROYEK</h1>
  <div class="red-line"></div>
</div>

<section id="section-proyek">
  <div class="container">
    <div class="proyek">
      <div class="proyek-image-wrapper">
        <img src="{% static 'images/shn.png' %}" alt="" />
      </div>
      <div class="proyek-text-wrapper">
        <h1>Simposium Hukum Nasional 2019</h1>
        <p>
          Website SHN 2019 merupakan website registrasi dan berita untuk
          kepanitiaan SHN 2019. Proyek ini saya lakukan bersama dua teman saya
          menggunakan HTML, CSS dan JavaScript.
        </p>
        <a href="https://shn.law.ui.ac.id/" class="button-website">
          Lihat website
        </a>
      </div>
    </div>

    <div class="proyek">
      <div class="proyek-image-wrapper">
        <img src="{% static 'images/github-finder.png' %}" alt="" />
      </div>
      <div class="proyek-text-wrapper bg-blue">
        <h1 class="white-font">Github Profile Finder</h1>
        <p class="white-font">
          Website ini merupakan proyek personal untuk melatih skill Asynchronus
          JavaScript dan API call. Di sini saya menggunakan GitHub API untuk
          mendapat data setiap user GitHub dengan menulis nama mereka.
        </p>
        <a
          href="https://reynardryanda.github.io/github-profile-finder/"
          class="button-website"
        >
          Lihat website
        </a>
      </div>
    </div>

    <div class="proyek">
      <div class="proyek-image-wrapper">
        <img src="{% static 'images/article-news.png' %}" alt="" />
      </div>
      <div class="proyek-text-wrapper">
        <h1>News Grid</h1>
        <p>
          Proyek personal ini saya lakukan untuk melatih HTML dan CSS saya. Saya
          menggunakan grid system untuk membuat bagian-bagian tertentu. website
          ini juga memiliki beberapa page untuk mengasah pengetahuan saya
          mengenai HTML.
        </p>
        <a
          href="https://reynardryanda.github.io/news-grid/"
          class="button-website"
        >
          Lihat website
        </a>
      </div>
    </div>
  </div>
</section>

<div id="kontak"></div>
<div class="lead-text">
  <h1>KONTAK SAYA</h1>
  <div class="red-line"></div>
</div>

<div class="bg-blue">
  <div class="container kontak">
    <div class="kontak-saya">
      <div class="kontak-text-wrapper white-font">
        <h1>Mari kita ngobrol.</h1>
      </div>
      <div class="icons white-font">
        <a href="https://www.linkedin.com/in/reynardryanda/"
          ><i class="fab fa-linkedin"></i
        ></a>
        <a href="https://line.me/ti/p/c07R3UUOds"
          ><i class="fab fa-line"></i
        ></a>
        <a href="https://twitter.com/reynardryanda"
          ><i class="fab fa-twitter-square"></i
        ></a>
        <a href="https://www.facebook.com/reynard.ryanda"
          ><i class="fab fa-facebook-square"></i
        ></a>
        <a href="https://www.instagram.com/reynardryanda/"
          ><i class="fab fa-instagram"></i
        ></a>
      </div>
    </div>
    <div class="form">
      <div class="form-wrapper">
        <form>
          <div class="input-wrapper">
            <input type="text" placeholder="Nama" />
          </div>
          <div class="input-wrapper">
            <input type="text" placeholder="Email" />
          </div>
          <div class="input-wrapper">
            <textarea cols="30" rows="10" placeholder="Pesan"></textarea>
          </div>
          <div class="button-submit">
            <button type="submit" value="">Kirim</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

jadwalKegiatan/templates/jadwal.html
{% extends "base.html" %} {% block content %} {% load static %}
<form action="" method="POST" style="display: flex; justify-content: center; align-items: center; flex-direction: column">
  {% csrf_token %}
  <table >
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit" style="margin: auto"/>
</form>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nama Kegiatan</th>
      <th scope="col">Kategori</th>
      <th scope="col">Tempat</th>
      <th scope="col">Jam</th>
      <th scope="col">Tanggal</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    {% for kegiatan in jadwal %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ kegiatan.kegiatan }}</td>
      <td>{{ kegiatan.kategori }}</td>
      <td>{{ kegiatan.tempat }}</td>
      <td>{{ kegiatan.jam }}</td>
      <td>{{ kegiatan.tanggal }}</td>
      <td><a href="{% url 'jadwal:delete' kegiatan.id %}">Hapus</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}